export const commands = {
    "about": [
        "<br>",
        "Hey, I’m Brekke 👨🏻‍💻",
        "<br>",
        "I’m a software engineer, a problem solver and an all around team player.", 
        "I typed my first “Hello, World!” in BASIC way back in 2007 and have been writing", 
        "and debugging code ever since! But before embarking on my coding journey,",
        "I studied kinesiology and biomechanics. I spent a few years building exoskeletons and", 
        "conducting crucial injury prevention research with the U.S. Army as a research engineer.",
        "<br>",
        "Fast forward to the present, and I've worked at an AI tech startup where I honed", 
        "my backend engineering skills and fed millions of data points into the AI engines.", 
        "Along the way, I've mastered a new programming language (Go) and crafted custom CLI", 
        "applications to streamline workflows. I've also dabbled in a little <a href=\"https://www.instagram.com/p/CvGGUlOuaYC/?utm_source=ig_web_copy_link\" target=\"_blank\" class=\"link\">community service</a>...", 
        "(hint: you can spot me in the black hat and green shirt 👀)",
        "<br>",
        "Now, I'm on the lookout for new job opportunities and if you happen to have any", 
        "on the horizon, I'm all ears! 🚀 Let's connect.",
        "<br>",
    ],
    "help": [
        "<br>",
        '<span class="command">about</span>          A little about Brekke',
        '<span class="command">resume</span>         Link to my current resume',
        '<span class="command">socials</span>        Display social profiles',
        '<span class="command">projects</span>       View some of my coding projects',
        '<span class="command">skills</span>         Some of my favorite tech in my toolbox',
        '<span class="command">history</span>        View command history',
        '<span class="command">help</span>           List of useable commands',
        '<span class="command">contact</span>        Info to get in touch',
        '<span class="command">clear</span>          Clear terminal',
        '<span class="command">banner</span>         Display the header',
        '<span class="command">hint</span>           Clue for the easter eggs',
        "<br>",
    ],
    "banner": [
        "<br>",
        ' ______     ______     ______     __  __     __  __     ______        ______     ______     ______     ______     __   __    ',
        '/\\  == \\   /\\  == \\   /\\  ___\\   /\\ \\/ /    /\\ \\/ /    /\\  ___\\      /\\  ___\\   /\\  == \\   /\\  ___\\   /\\  ___\\   /\\ "-.\\ \\   ',
        'Ø\\ \\  __<   \\ \\  __<   \\ \\  __\\   \\ \\  _"-.  \\ \\  _"-.  \\ \\  __\\      \\ \\ \\__ \\  \\ \\  __<   \\ \\  __\\   \\ \\  __\\   \\ \\ \\-.  \\  ',
        ' \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_\\ \\_\\  \\ \\_____\\     \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\\\"\\_\\ ',
        '  \\/_____/   \\/_/ /_/   \\/_____/   \\/_/\\/_/   \\/_/\\/_/   \\/_____/      \\/_____/   \\/_/ /_/   \\/_____/   \\/_____/   \\/_/ \\/_/ ',
        '                                                                                                                            ',
        "<span class=\"spaceman\">        _..._</span>",
        "<span class=\"spaceman\">      .'  ._''.      _</span>",
        "<span class=\"spaceman\">     /  /      \\   _/ \\</span>",
        "<span class=\"spaceman\">   .-| |:.      |  |   |</span>",
        "<span class=\"spaceman\">   |  \\ \\:.    /.-'-./</span>",
        "<span class=\"spaceman\">   | .-'-;:__.'    =/</span>",
        "<span class=\"spaceman\">   .'=  *=|NASA _.='</span>",
        "<span class=\"spaceman\">  /   _.  |    ;</span>",
        "<span class=\"spaceman\"> ;-.-'|    \\   |</span>",
        "<span class=\"spaceman\">/   | \\    _\\  _\\</span>",
        "<span class=\"spaceman\">\\__/'._;.  ==' ==\\</span>",
        "<span class=\"spaceman\">         \\    \\   |</span>",
        "<span class=\"spaceman\">         /    /   /</span>",
        "<span class=\"spaceman\">         /-._/-._/</span>",
        "<span class=\"spaceman\">         \\   `\\  \\</span>",
        "<span class=\"spaceman\">          `-._/._/</span>",
        "<span></span>",
        "<span class=\"message\">Welcome to my interactive terminal! Built with my favorite <a href=\"https://www.nordtheme.com/\" target=\"_blank\" class=\"link\">nord</a> stylings and some fun easter eggs for you to enjoy. Thanks for stopping by 😎</span>",
        "<span class=\"info\">Click the cursor and type <span class=\"command\">'help'</span> to see list of commands and learn a little more about me!</span>",
        "<br>",
    ],
    "contact": [
        "<br>",
        "Please reach out if you have any projects you'd like to work on together or open roles you think I'd be a good fit for! :)",
        "Email: brekke.andrew.green@gmail.com",
        "<br>",
    ],
    "socials": [
        "<br>",
        'Github:        <a href="https://github.com/Brekke-Green" target="_blank" class="link">github.com/Brekke-Green</a>',
        'LinkedIn:      <a href="https://www.linkedin.com/in/brekke-andrew-green/" target="_blank" class="link">linkedin.com/brekke-andrew-green</a>',
        'Instagram:     <a href="https://www.instagram.com/brekke__green/" target="_blank" class="link">instagram.com/brekke__green</a>',
        "<br>",
    ],
    "skills": [
        "<br>",
        "A current list of technologies I work with.",
        "I'm always working to update and diversify this list!",
        "<br>",
        'Python',
        'Javascript',
        'Go',
        'Django',
        'Ruby on Rails',
        'Docker',
        'AWS',
        'SQL',
        'Redis',
        'Artificial Intelligence (AI)',
        'Git',
        'Linux',
        'Cloud Computing',
        'Vite',
        'Airflow',
        'React.js',
        'Node.js',
        'Neovim',
        'Data Engineering',
        "<br>",
    ],
    "projects": [
        "<br>",
        "Try them out!",
        "<br>",
        '<a href="https://disarray-app.herokuapp.com/#/" target="_blank" class="link">Disarray</a>',
        "Multiplayer online Boggle Game built with a retro styling. Developed using Socket.IO to connect various players to a game server.",
        "<br>",
        "Technology used: MongoDB, Express.js, React,",
        "Redux, Node.js, Socket.IO, HTML, CSS, Heroku",
        "<br>",
        '<a href="https://brekke-green.github.io/dslr_u_sure/" target="_blank" class="link">DSLR U SURE?</a>',
        "All-in-one learning tool for understanding how camera controls (e.g., aperture, shutter speed and ISO) work in manual mode.",
        "<br>",
        "Technology used: Javascript, HTML, CSS, Node.js, webpack, Github Pages",
        "<br>",
    ],
    "resume": [
        "<br>",
        '<a href="https://brekke-green.github.io/BrekkeGreen_Resume_2024.pdf" target="_blank" class="link">Check out my resume here!</a>',
        "<br>",
    ],
    "hint": [
        "<br>",
        "Try opening your favorite text <span class=\"command\">'editors'</span>... 🤫",
        "<br>",
    ],
}

export const editors = [
    "<br>",
    "emacs",
    "code .",
    "jupyter notebook",
    "vi .",
    "vim .",
    "nvim .",
    "<br>",
]
