export const commands = {
    "about": [
        "<br>",
        '<iframe src="https://giphy.com/embed/iofbYa67AbBg4" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>',
        "<br>",
    ],
    "help": [
        "<br>",
        '<span class="command">about</span>          A little about Brekke',
        '<span class="command">resume</span>         Link to my current resume',
        '<span class="command">socials</span>        Display social profiles',
        '<span class="command">projects</span>       View some of my coding projects',
        '<span class="command">skills</span>         List of skills/tech in the toolbox',
        '<span class="command">history</span>        View command history',
        '<span class="command">help</span>           List of useable commands',
        '<span class="command">contact</span>        Info to reach out',
        '<span class="command">clear</span>          Clear terminal',
        '<span class="command">banner</span>         Display the header',
        "<br>",
    ],
    "banner": [
        "<br>",
        ' ______     ______     ______     __  __     __  __     ______        ______     ______     ______     ______     __   __    ',
        '/\\  == \\   /\\  == \\   /\\  ___\\   /\\ \\/ /    /\\ \\/ /    /\\  ___\\      /\\  ___\\   /\\  == \\   /\\  ___\\   /\\  ___\\   /\\ "-.\\ \\   ',
        'Ø\\ \\  __<   \\ \\  __<   \\ \\  __\\   \\ \\  _"-.  \\ \\  _"-.  \\ \\  __\\      \\ \\ \\__ \\  \\ \\  __<   \\ \\  __\\   \\ \\  __\\   \\ \\ \\-.  \\  ',
        ' \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_\\ \\_\\  \\ \\_____\\     \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\\\"\\_\\ ',
        '  \\/_____/   \\/_/ /_/   \\/_____/   \\/_/\\/_/   \\/_/\\/_/   \\/_____/      \\/_____/   \\/_/ /_/   \\/_____/   \\/_____/   \\/_/ \\/_/ ',
        '                                                                                                                            ',
        "<span class=\"spaceman\">        _..._</span>",
        "<span class=\"spaceman\">      .'  ._''.      _</span>",
        "<span class=\"spaceman\">     /  /      \\   _/ \\</span>",
        "<span class=\"spaceman\">   .-| |:.      |  |   |</span>",
        "<span class=\"spaceman\">   |  \\ \\:.    /.-'-./</span>",
        "<span class=\"spaceman\">   | .-'-;:__.'    =/</span>",
        "<span class=\"spaceman\">   .'=  *=|NASA _.='</span>",
        "<span class=\"spaceman\">  /   _.  |    ;</span>",
        "<span class=\"spaceman\"> ;-.-'|    \\   |</span>",
        "<span class=\"spaceman\">/   | \\    _\\  _\\</span>",
        "<span class=\"spaceman\">\\__/'._;.  ==' ==\\</span>",
        "<span class=\"spaceman\">         \\    \\   |</span>",
        "<span class=\"spaceman\">         /    /   /</span>",
        "<span class=\"spaceman\">         /-._/-._/</span>",
        "<span class=\"spaceman\">         \\   `\\  \\</span>",
        "<span class=\"spaceman\">          `-._/._/</span>",
        "<span></span>",
        "<span class=\"info\">Click the cursor and type <span class=\"command\">'help'</span> to see list of commands!</span>",
        "<br>",
    ],
    "contact": [
        "<br>",
        "Please reach out if you have any projects you'd like to work on together or open roles you think I'd be a good fit for! :)",
        "Email: brekke.andrew.green@gmail.com",
        "<br>",
    ],
    "socials": [
        "<br>",
        'Github:        <a href="https://github.com/Brekke-Green" target="_blank" class="link">github.com/Brekke-Green</a>',
        'LinkedIn:      <a href="https://www.linkedin.com/in/brekke-andrew-green/" target="_blank" class="link">linkedin.com/brekke-andrew-green</a>',
        'Instagram:     <a href="https://www.instagram.com/brekke__green/" target="_blank" class="link">instagram.com/brekke__green</a>',
        "<br>",
    ],
    "skills": [
        "<br>",
        'Python',
        'Javascript',
        'Go',
        'Django',
        'Ruby on Rails',
        'Docker',
        'AWS',
        'SQL',
        'Redis',
        'Artificial Intelligence (AI)',
        'Git',
        'Linux',
        'Cloud Computing',
        'React',
        'Node.js',
        'Data Engineering',
        "<br>",
    ],
    "projects": [
        "<br>",
        '<a href="https://disarray-app.herokuapp.com/#/" target="_blank" class="link">Disarray</a>',
        '<a href="https://brekke-green.github.io/dslr_u_sure/" target="_blank" class="link">DSLR U SURE?</a>',
        "<br>",
    ],
    "resume": [
        "<br>",
        '<a href="https://brekke-green.github.io/BrekkeAndrewGreen.pdf/" target="_blank" rel="noopener noreferrer" class="link">Check out my resume here!</a>',
        "<br>",
    ],
}

export const editors = [
    "vi .",
    "vim .",
    "nvim .",
    "emacs",
    "code .",
]
