export const commands = {
    "help": [
        "<br>",
        '<span class="command">about</span>          A little about Brekke',
        '<span class="command">social</span>         Display social networks',
        '<span class="command">projects</span>       View coding projects',
        '<span class="command">history</span>        View command history',
        '<span class="command">help</span>           List of useable commands',
        '<span class="command">contact</span>        Email/Phone. Please reach out!!',
        '<span class="command">clear</span>          Clear terminal',
        '<span class="command">banner</span>         Display the header',
        "<br>",
    ],
    "banner": [
        "<br>",
        ' ______     ______     ______     __  __     __  __     ______        ______     ______     ______     ______     __   __    ',
        '/\\  == \\   /\\  == \\   /\\  ___\\   /\\ \\/ /    /\\ \\/ /    /\\  ___\\      /\\  ___\\   /\\  == \\   /\\  ___\\   /\\  ___\\   /\\ "-.\\ \\   ',
        '\\ \\  __<   \\ \\  __<   \\ \\  __\\   \\ \\  _"-.  \\ \\  _"-.  \\ \\  __\\      \\ \\ \\__ \\  \\ \\  __<   \\ \\  __\\   \\ \\  __\\   \\ \\ \\-.  \\  ',
        ' \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_\\ \\_\\  \\ \\_____\\     \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\\\"\\_\\ ',
        '  \\/_____/   \\/_/ /_/   \\/_____/   \\/_/\\/_/   \\/_/\\/_/   \\/_____/      \\/_____/   \\/_/ /_/   \\/_____/   \\/_____/   \\/_/ \\/_/ ',
        '                                                                                                                            ',
        "        _..._",
        "      .'  ._''.      _",
        "     /  /      \\   _/ \\",
        "   .-| |:.      |  |   |",
        "   |  \\ \\:.    /.-'-./",
        "   | .-'-;:__.'    =/",
        "   .'=  *=|NASA _.='",
        "  /   _.  |    ;",
        " ;-.-'|    \\   |",
        "/   | \\    _\\  _\\",
        "\\__/'._;.  ==' ==\\",
        "         \\    \\   |",
        "         /    /   /",
        "         /-._/-._/",
        "         \\   `\\  \\",
        "          `-._/._/",
        "<br>",
    ],
}
